$(document).ready(function(){
    $("#info").click(function(){
        $(".info-tab").show();
        $(".education-tab").hide();
        $(".work-tab").hide();
        $(".programming-tab").hide();
        $(".language-tab").hide();
        $("#info").parent().addClass("active");
        $("#educacao").parent().removeClass("active");
        $("#experiencia").parent().removeClass("active");
        $("#linguagens").parent().removeClass("active");
        $("#linguas").parent().removeClass("active");
    });
    $("#educacao").click(function(){
        $(".info-tab").hide();
        $(".education-tab").show();
        $(".work-tab").hide();
        $(".programming-tab").hide();
        $(".language-tab").hide();
        $("#info").parent().removeClass("active");
        $("#educacao").parent().addClass("active");
        $("#experiencia".parent()).removeClass("active");
        $("#linguagens").parent().removeClass("active");
        $("#linguas").parent().removeClass("active");
    });
    $("#experiencia").click(function(){
        $(".info-tab").hide();
        $(".education-tab").hide();
        $(".work-tab").show();
        $(".programming-tab").hide();
        $(".language-tab").hide();
        $("#info").parent().removeClass("active");
        $("#educacao").parent().removeClass("active");
        $("#experiencia").parent().addClass("active");
        $("#linguagens").parent().removeClass("active");
        $("#linguas").parent().removeClass("active");
    });
    $("#linguagens").click(function(){
        $(".info-tab").hide();
        $(".education-tab").hide();
        $(".work-tab").hide();
        $(".programming-tab").show();
        $(".language-tab").hide();
        $("#info").parent().removeClass("active");
        $("#educacao").parent().removeClass("active");
        $("#experiencia").parent().removeClass("active");
        $("#linguagens").parent().addClass("active");
        $("#linguas").parent().removeClass("active");
    });
    $("#linguas").click(function(){
        $(".info-tab").hide();
        $(".education-tab").hide();
        $(".work-tab").hide();
        $(".programming-tab").hide();
        $(".language-tab").show();
        $("#info").parent().removeClass("active");
        $("#educacao").parent().removeClass("active");
        $("#experiencia").parent().removeClass("active");
        $("#linguagens").parent().removeClass("active");
        $("#linguas").parent().addClass("active");
    });
});